# Generated by Django 5.2.17 on 2026-08-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(default='Data Analytics', max_length=100)),
                ('summary', models.TextField(help_text='Business problem and project overview')),
                ('key_insight', models.TextField(blank=True, default='', help_text='Primary analytical insight or business impact')),
                ('tools', models.JSONField(blank=True, default=list, help_text="List of tools used, e.g. ['SQL', 'Python']")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('cover_image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Section Heading'), ('subheading', 'Subheading'), ('text', 'Text / Description'), ('image', 'Image & Chart'), ('metric', 'KPI / Metric Callout'), ('quote', 'Key Takeaway / Quote')], default='text', max_length=20)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_blocks/')),
                ('image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('image_caption', models.CharField(blank=True, default='', max_length=255)),
                ('metric_value', models.CharField(blank=True, default='', max_length=100)),
                ('metric_label', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
